### ISSUE TITLE
uasyncio error on PyCom boards

### ISSUE THREAD

**Issue by DanielIbaseta** [pfalcon/pycopy-lib#29]
Hello, Im working with [uasyncio](https://github.com/pfalcon/micropython-lib/tree/master/uasyncio/uasyncio) for a while now and I notice that when using it in Pycom (GPy and FiPy) boards, the amount of concurrent request i can make to an asynchronous server is very limited (less than 10). I found that in other ESP32 boards the concurrency is better (more than 100) and I don't know if I'm facing with a hardware or a software problem so I will expose what I'm doing.

First I have a [picoweb](https://github.com/pfalcon/picoweb) server running on the board, then I run a bunch of other asynchronous tasks and they live happily together until I start to send requests to the web server. I use the ab (Apache Benchmark) tool to simulate 100 petitions with a concurrency of 10 or more and it makes the uasyncio library crash every time as seen here:
```
    File "/flash/lib/picoweb/__init__.py", line 298, in run
    File "/flash/lib/uasyncio/core.py", line 161, in run_forever
    File "/flash/lib/uasyncio/core.py", line 116, in run_forever
    File "/flash/lib/uasyncio/__init__.py", line 247, in start_server
OSError: 23
ets Jun  8 2016 00:22:57
```

This is the line 247:
```
    s2, client_addr = s.accept()
```

It does not seem to be a memory problem, as the Pycom GPy I'm using has 520KB of RAM and also my code works nicely if the petitions are done slower. It isn't a picoweb problem, as it works perfectly in other ESP32 microcontrollers, so I thought someone here might know the issue.

Thank you for your time.

**Comment by pfalcon** [comment]
Thanks for the report. I don't have/use PyCom boards, so wouldn't be able to help with these. And fairly speaking, your report answers it itself: if it works well on other ESP32 boards, then the problem must be PyCom MicroPython fork.
