### ISSUE TITLE
cgi: Issues due to os.environ not implemented (workaround available)

### ISSUE THREAD

**Issue by markw77** [pfalcon/pycopy-lib#34]
Hi, there is libcgi which I would like to use but the html form data are not populated possibly becasue of os.environ not implemented:
environ = {"WARNING": "NOT_IMPLEMENTED"}

Could you please give any hint what is the best way to fix it ? ( could be popualting os.environ by env system call ? )

**Comment by pfalcon** [comment]
If *you* want to get a particular env var, the best way to do that is using os.getenv(). No idea about libcgi though. (What is it btw?)

**Comment by markw77** [comment]
I mean this: https://github.com/pfalcon/micropython-lib/tree/master/cgi
Yes, I am aware about os.getenv() but normal CPython has its os.environ prepopulated

**Comment by markw77** [comment]
That would fix cgi module:

os.environ["QUERY_STRING"] = os.getenv("QUERY_STRING")
os.environ["CONTENT_TYPE"] = os.getenv("CONTENT_TYPE")
os.environ["CONTENT_LENGTH"] = os.getenv("CONTENT_LENGTH")
os.environ["HTTP_COOKIE"] = os.getenv("HTTP_COOKIE")
os.environ["HTTP_USER_AGENT"] = os.getenv("USER_AGENT")
os.environ["REMOTE_ADDR"] = os.getenv("REMOTE_ADDR")
os.environ["REMOTE_HOST"] = os.getenv("REMOTE_HOST")
os.environ["REQUEST_METHOD"] = os.getenv("REQUEST_METHOD")
os.environ["SCRIPT_FILENAME"] = os.getenv("SCRIPT_FILENAME")
os.environ["SCRIPT_NAME"] = os.getenv("SCRIPT_NAME")
os.environ["SERVER_NAME"] = os.getenv("SERVER_NAME")
os.environ["SERVER_SOFTWARE"] = os.getenv("SERVER_SOFTWARE")

You could add it to the cgi FieldStorage __init__ method

**Comment by pfalcon** [comment]
Ok, basic support for os.environ (getting vars via it) was implemented in pycopy-os 0.9.
