### ISSUE TITLE
uasyncio "example_http_server.py" fails with EAGAIN

### ISSUE THREAD

**Issue by larsks** [pfalcon/pycopy-lib#47]
I'm running pycopy built from 82ec8df:

```
Pycopy v3.0.5-4-g82ec8dfd3a on 2020-03-16; ESP module with ESP8266                      │
Type "help()" for more information.                                                    │
>>> import server                                                                      │
```

I'm trying to run [example_http_server.py](https://github.com/pfalcon/pycopy-lib/blob/master/uasyncio/example_http_server.py). I have `uasyncio/__init__.py` and `uasyncio/core.py`, both from pfalcon/pycopy-lib@5325a960d.  When I `import example_http_server`, I get:

```
>>> import example_http_server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example_http_server.py", line 20, in <module>
  File "uasyncio/core.py", line 116, in run_forever
  File "uasyncio/__init__.py", line 266, in start_server
OSError: [Errno 11] EAGAIN
```

Is this expected to work? Could there be something wrong with my environment that is causing this?

**Comment by pfalcon** [comment]
As READMEs for both Pycopy and pycopy-lib say, the reference configuration for both is the "Unix" port: https://github.com/pfalcon/pycopy#the-unix-version . That's what known to work. Please reproduce/triage any issues you face against the Unix port to see whether it's a problem of pycopy/pycopy-lib or of the underlying hardware platform.

**Comment by larsks** [comment]
Hi, sorry for being unclear. The example seems to work fine on the unix port, but the same code fails as described on the esp8266 port. I've worked around it for now with a non-asyncio solution.

**Comment by pfalcon** [comment]
Pycopy inherits support for baremetal systems from the upstream MicroPython. At this time, I don't work on that code. And indeed, no baremetal system works as correctly as the reference platform (i.e. POSIX). There's ongoing work to fix those issue in upstream, but it seems, they're not yet there. I'm merging the fixes regularly, and if you'd like to help that, you'd need to submit an upstream report with a minimal reproduction code (i.e. working directly with `usocket`/`uselect` modules, bypassing `uasyncio`).
