### ISSUE TITLE
zlib : ' object has no attribute 'func'

### ISSUE THREAD

**Issue by QAMU** [pfalcon/pycopy-lib#51]
hello everyone,
please what is the problem in this :
```
File "zlib.py", line 9, in <module>
AttributeError: 'NoneType' object has no attribute 'func'
```
I have also the **ffi.py** lib but the same problem

**Comment by pfalcon** [comment]
Please see https://www.chiark.greenend.org.uk/~sgtatham/bugs.html .

**Comment by pmp-p** [comment]
The problem is in the way ffilib.open deals with versions for shared library ( or static libc ) on  operating system which OP should really give some info about.

it not a zlib problem but an ffilib problem and i've already seen it in the past. it probably could be fixed with more information.

**Comment by pfalcon** [comment]
Yes, and the "How to Report Bugs Effectively" guide, quoted above, should help with providing more, relevant, information.
