### ISSUE TITLE
uasyncio: How to create tasks so they will be run immediatelly?

### ISSUE THREAD

**Issue by iBobik** [pfalcon/pycopy-lib#54]
I try to control two relays with different delays concurently. Each of relay has own config and own task.

```
from machine import Pin
import uasyncio as asyncio
loop = asyncio.get_event_loop()
import utime
import logging
log = logging.getLogger("relay")
import events


# Load config and initiate pins
import config
relays = config.modules['relay']['relays']
for r in relays:
	r.update({
		'pin_obj': Pin(r['pin'], Pin.OUT)
	})


@events.on('card.card_validated')
def on_card_validated(card):
	for config in relays:
		loop.create_task(relay_task(config, card))


async def relay_task(config, card):
	if 'open_after' in config:
		log.info("Will open relay on pin %d in %d seconds", config['pin'], config['open_after'])
		await asyncio.sleep(config['open_after'])

	log.info("Opening relay on pin %d for %d seconds", config['pin'], config['close_after'])
	config['pin_obj'].on()
	await asyncio.sleep(config['close_after'])
	config['pin_obj'].off()

```

This code works, but there is delay few seconds between create_task and relay_task start. I need to have the delay up to one second.

Pycopy v3.0.6
Modules has current versions from PyPi.

Is it bug or I use it incorrectly?

Thank you for help.

**Comment by pfalcon** [comment]
Tasks do run immediately (or more specifically, ASAP).

From a quick look, I don't see something obviously wrong with the above code, but it's neither minimal nor complete case (http://sscce.org/). What steps did you take to investigate and debug the issue?

**Comment by pfalcon** [comment]
No response, assuming issue is resolved. Closing. For future cases, please follow guidelines in the link posted.

**Comment by iBobik** [comment]
Sorry, hobby project was postponed until I will have a time for it again :-)

**Comment by pfalcon** [comment]
> Sorry, hobby project was postponed until I will have a time for it again :-)

That's ok, feel free to resubmit/reopen when a testcase is available.

I'm from my side polishing/extending existing tests for uasyncio, and make sure they're actually run regularly.
