### ISSUE TITLE
upip - cpython issues

### ISSUE THREAD

**Issue by iot49** [pfalcon/pycopy-lib#57]
`micropython-cpython-upip` has a few issues on Python 3.8:

1. Line 70 in `upip.py`: Python 3.8 does not support the `size` argument in `open`:

```
outf.write(file_buf, size=sz)
```

Fix:

```
outf.write(file_buf)
```

The following works:

2. `gc`: `gc.mem_free` and `gc.mem_free` don't exist.

Workaround:

```
import gc
gc.mem_free = lambda : 1000000
gc.mem_alloc = lambda : 100000

import upip # now works as expected
```

**Comment by pfalcon** [comment]
> micropython-cpython-upip

There's no such package in this project. Try pycopy-cpython-upip.

**Comment by iot49** [comment]
Thanks, that fixed it!
