### ISSUE TITLE
ubinascii

### ISSUE THREAD

**Issue by Dan-Essin** [pfalcon/pycopy-lib#65]
The file
https://files.pythonhosted.org/packages/a3/4f/c3ef929e2f2269c1007d13e668ae1a68023b202eae663bd47a0953b67f42/micropython-cpython-ubinascii-0.0.tar.gz

contains neither source code nor an executable

[micropython-cpython-ubinascii-0.0.tar.gz](https://github.com/pfalcon/pycopy-lib/files/6565184/micropython-cpython-ubinascii-0.0.tar.gz)

**Comment by pfalcon** [comment]
That could happen, not all modules in pycopy-lib are implemented yet. Modules are usually implemented on demand by people who need them. How did you come about that module and what do you need it for?
