### ISSUE TITLE
urequest module error when calling a HTTPS url

### ISSUE THREAD

**Issue by netomarin** [pfalcon/pycopy-lib#66]
When executing a POST to an HTTPS endpoint, I get an error from the function [`request`](https://github.com/pfalcon/pycopy-lib/blob/6000539115c930d085cdc50ff43dec19912da856/urequests/urequests/__init__.py#L41) at [line 88](https://github.com/pfalcon/pycopy-lib/blob/6000539115c930d085cdc50ff43dec19912da856/urequests/urequests/__init__.py#L88):
```
File "/lib/urequests/__init__.py", line 162, in post
File "/lib/urequests/__init__.py", line 88, in request
AttributeError: 'module' object has no attribute 'SSLContext'
```
Accordingo the ussl documentation, there is no such [function](https://docs.micropython.org/en/latest/library/ussl.html#functions) `ussl.SSLContext()`, the only method listed there is [`wrap_socket`](https://docs.micropython.org/en/latest/library/ussl.html#ussl.ussl.wrap_socket) which is called on [line 89](https://github.com/pfalcon/pycopy-lib/blob/6000539115c930d085cdc50ff43dec19912da856/urequests/urequests/__init__.py#L89), but against the ctx reference instead.

**Comment by pfalcon** [comment]
pycopy-lib is part of Pycopy ecosystem, please see https://github.com/pfalcon/pycopy-lib (description, README) regarding requirements needed to use pycopy-lib. There's definitely ussl.SSLContext class: https://pycopy.readthedocs.io/en/latest/library/ussl.html#ussl.SSLContext
