### ISSUE TITLE
'pip install micropython-upip' returned error

### ISSUE THREAD

**Issue by DesperateForHelpIntern** [pfalcon/pycopy-lib#67]
I wanted to import machine to micropython and upip seemed like it would make my day easier.  However when I typed the pip installer into the command prompt, this error appeared: 

ERROR: File "setup.py" not found for legacy project micropython-upip from https://files.pythonhosted.org/packages/29/81/52df27cb7d240190c1d3ddab0c081bd3296bedcce155eed9e7016c4d92f0/micropython-upip-1.2.6.tar.gz#sha256=b9c09fc2b65f877d945142e468e0f25b5f70e9f74e98e0f43ca030bd7f47e87f.

Suggestions?

**Comment by Kakcalu13** [comment]
Aw, this is ongoing issue?
