### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSLContext'

### ISSUE THREAD

**Issue by usr577** [pfalcon/pycopy-lib#79]
It returns `AttributeError: 'module' object has no attribute 'SSLContext'` when using the post option and says line 87, so `ctx = ussl.SSLContext()` is wrong. Using micropython version 1.19.1 on esp32

**Comment by alej0varas** [comment]
You can:

- remove line
`ctx = ussl.SSLContext()`

- replace `ctx` by `ussl`
`s = ussl.wrap_socket(s, server_hostname=host)`
