### ISSUE TITLE
[logging] sys.exc_info() function doesn't exist on ESP32

### ISSUE THREAD

**Issue by PolarGoose** [pfalcon/pycopy-lib#88]
**Micopython version:** v1.23.0
**Board:** ESP32 / WROOM

The error message when using the logging library:
```
  File "/lib/logging/__init__.py", line 72, in exception
AttributeError: 'module' object has no attribute 'exc_info'
MicroPython v1.23.0 on 2024-06-02; Generic ESP32 module with ESP32
```

**Comment by pfalcon** [comment]
This project has nothing to do with MicroPython or ESP32.

**Comment by PolarGoose** [comment]
@pfalcon,
> This project has nothing to do with MicroPython or ESP32.

Why is the logging implementation from this project packaged into [micropython-logging](https://pypi.org/project/micropython-logging/)?
